### Numpy

In [96]:
import numpy as np         ### numerical+python

In [97]:
arr=np.array([1,2,3,4,6,'hii'])   # create the array
arr

array(['1', '2', '3', '4', '6', 'hii'], dtype='<U11')

In [98]:
list_of_lists=np.array([[4,5,6],[1,2,3],[7,8,9]]) #multiple rows
list_of_lists

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

In [99]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [100]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [101]:
np.arange(1,20,4)

array([ 1,  5,  9, 13, 17])

In [102]:
np.arange(1,30,5)

array([ 1,  6, 11, 16, 21, 26])

In [103]:
np.arange(5,30,5)

array([ 5, 10, 15, 20, 25])

In [104]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [105]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [106]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [107]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [108]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [109]:
np.linspace(0,1,6)         #linspace means form i to j there is k-2 equal places between them

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [110]:
np.linspace(0,20,6)         #where in arange form i to i+nk till it exceed j

array([ 0.,  4.,  8., 12., 16., 20.])

In [111]:
np.linspace(1,10)       #by default it will take k=50

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [112]:
np.linspace(1,10,dtype=int)

array([ 1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,
        4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  7,
        7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10])

In [113]:
np.eye(12,dtype=int)      

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [114]:
np.random.rand(3,5)

array([[0.38763658, 0.92455829, 0.23155218, 0.96267647, 0.54660027],
       [0.71400942, 0.49702832, 0.42499334, 0.843389  , 0.2880987 ],
       [0.3690864 , 0.20439143, 0.971345  , 0.50535028, 0.69754538]])

In [115]:
np.random.randn(3,5)

array([[-1.22934296,  1.83539888,  1.48792156, -0.87519304, -0.24938675],
       [-1.16130015, -1.91890159,  0.66866324, -1.167455  , -1.11663493],
       [-0.96845682,  2.11095068,  1.76603063, -0.74917055,  0.32763466]])

In [116]:
np.random.randint(1,10)      #           int<10

5

In [117]:
np.random.rand(2,4,3)

array([[[0.27432894, 0.63398066, 0.84429254],
        [0.61353419, 0.52291766, 0.54067404],
        [0.28434685, 0.60294114, 0.59928932],
        [0.12098747, 0.15364724, 0.88900997]],

       [[0.07803708, 0.29390846, 0.77506715],
        [0.70950988, 0.5851444 , 0.25160489],
        [0.85874465, 0.82051921, 0.17602715],
        [0.04214406, 0.95349948, 0.7178311 ]]])

In [118]:
np.random.randn(2,4,3)

array([[[ 0.5010584 ,  1.03744265,  0.19433643],
        [ 1.23273636, -0.71163579,  1.59539727],
        [-0.02287254,  1.77044531,  1.13600886],
        [ 2.11677237,  0.37800769,  1.12999915]],

       [[-1.62539077,  1.85764127, -0.71377071],
        [ 1.27733986, -2.14880176, -0.63416864],
        [-2.63907646,  0.54393993,  1.0466654 ],
        [-0.35848371,  0.85127144, -1.67546937]]])

In [119]:
np.random.randint(1,20,100)        #100 int from 1 to 19

array([ 1,  7, 11, 19,  1,  6,  7, 12, 13,  2, 16, 18,  1, 10, 10, 12,  5,
        3,  3, 13,  9, 18, 19, 18, 18,  7, 18,  8, 17, 14, 14, 16, 12, 10,
       13,  1, 19,  9,  6,  5,  3, 17, 13,  2,  7,  2, 11,  1, 16,  4, 11,
        9,  6,  8, 17,  7,  2,  3, 17, 19, 10, 16, 18, 10,  6,  9,  1, 10,
       11, 11,  5,  8,  5,  1,  2,  7,  3,  1, 11,  3,  8, 16, 13, 13, 10,
       13, 11, 11, 12, 15, 10, 18,  6, 14,  1, 11,  8, 11, 10,  8])

In [120]:
np.random.randint(2,3,5)

array([2, 2, 2, 2, 2])

In [121]:
sample_array1=np.arange(50)
sample_array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [122]:
sample_array2=np.arange(30)
sample_array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [123]:
sample_array3=np.random.rand(10)
sample_array3

array([0.22505084, 0.68384569, 0.75107418, 0.99340255, 0.25690964,
       0.05581414, 0.62347377, 0.12641094, 0.95934527, 0.55609375])

In [124]:
sample_array4=np.arange(1,30,2)  # i to j-1 with k diffrence
sample_array4

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [125]:
sample_array1.reshape(5,10)        # i*j should be 50

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [126]:
sample_array2.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [127]:
rand_array=np.random.randint(0,100,50)
rand_array

array([90,  3, 24, 94, 77, 16, 90, 61, 39, 24, 43, 10, 72, 91, 42, 19, 86,
       10, 28, 72,  4, 76, 56, 12,  0, 88,  3, 21, 18, 51, 37, 17,  0,  6,
       51,  5, 25, 59, 20, 68, 64, 51, 21,  6, 22,  1, 34,  2, 40, 90])

In [128]:
rand_array2=np.random.rand(2,10,5)
rand_array2

array([[[6.56934357e-01, 3.59114703e-01, 7.93202649e-01, 7.96057059e-01,
         6.32784679e-01],
        [4.80513198e-01, 8.19218893e-02, 2.49920453e-01, 6.78215594e-01,
         4.18886838e-01],
        [7.16699350e-01, 9.80619908e-02, 5.65425636e-01, 5.20040344e-01,
         6.30416600e-01],
        [2.23321870e-01, 7.99522673e-01, 6.09521227e-01, 8.85547135e-01,
         6.58365410e-01],
        [3.89808882e-02, 7.46777600e-01, 1.23669435e-01, 4.26097998e-01,
         6.89543064e-01],
        [5.44534852e-01, 2.88070292e-01, 9.03410006e-01, 4.28312449e-01,
         8.47095389e-01],
        [5.39921124e-01, 7.76554122e-01, 3.82255294e-01, 6.80276804e-01,
         6.19184145e-01],
        [1.23624520e-02, 7.73466505e-01, 9.48102601e-01, 8.81102471e-01,
         1.19090281e-01],
        [4.45824983e-01, 9.76638835e-01, 4.11507030e-01, 1.04773781e-01,
         9.35848880e-01],
        [1.18188889e-01, 3.14066895e-01, 5.58885549e-01, 6.91026403e-01,
         5.92875675e-01]],

       [

In [129]:
rand_array.min() 

0

In [130]:
rand_array.max()

94

In [131]:
rand_array.argmin()          #index of the min value

24

In [132]:
rand_array.argmax()             #index of the max value

3

In [133]:
a=np.random.rand(2,3)
a

array([[0.58302479, 0.07853711, 0.39973559],
       [0.29694235, 0.89087504, 0.86996496]])

In [134]:
a.T            #transpose of a

array([[0.58302479, 0.29694235],
       [0.07853711, 0.89087504],
       [0.39973559, 0.86996496]])

In [135]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [136]:
sample_array[5]

15

In [137]:
sample_array[2:5]

array([12, 13, 14])

In [138]:
sample_matrix=np.array(([1,2,3],[5,6,7],[4,5,5]))
sample_matrix

array([[1, 2, 3],
       [5, 6, 7],
       [4, 5, 5]])

In [139]:
sample_matrix.T

array([[1, 5, 4],
       [2, 6, 5],
       [3, 7, 5]])

In [140]:
sample_matrix[1][1]          #i,j element

6

In [141]:
sample_matrix[1]         #first row

array([5, 6, 7])

In [142]:
sample_matrix[0:2]          # i to j-1 roe

array([[1, 2, 3],
       [5, 6, 7]])

In [143]:
sample_matrix[1:0]        

array([], shape=(0, 3), dtype=int32)

In [144]:
sample_matrix[1:]        # all row from 1

array([[5, 6, 7],
       [4, 5, 5]])

In [145]:
sample_matrix[:4]   

array([[1, 2, 3],
       [5, 6, 7],
       [4, 5, 5]])

In [146]:
sample_matrix[0:2]

array([[1, 2, 3],
       [5, 6, 7]])

In [147]:
sample_matrix[0:]

array([[1, 2, 3],
       [5, 6, 7],
       [4, 5, 5]])

In [148]:
sample_matrix[1,0:2]        # ith row element form m to n-1

array([5, 6])

In [149]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [150]:
sample_array+sample_array   #correponding index add

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [151]:
sample_array5=np.random.rand(2,5)
sample_array5

array([[0.57963879, 0.38527972, 0.68896192, 0.87613209, 0.07493461],
       [0.87658902, 0.0342117 , 0.86534298, 0.5176284 , 0.24407679]])

In [152]:
sample_array5+sample_array5

array([[1.15927758, 0.77055943, 1.37792384, 1.75226418, 0.14986922],
       [1.75317803, 0.0684234 , 1.73068596, 1.03525679, 0.48815358]])

In [153]:
sample_array6=np.random.randn(2,5)
sample_array6

array([[-0.85358796,  0.93276325,  0.50107051, -0.89466468,  1.86655667],
       [ 0.57715383,  0.59010281,  0.65903211, -0.97765636,  0.37667548]])

In [154]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [155]:
np.min(sample_array)

1

In [156]:
np.max(sample_array)

19

In [157]:
np.argmax(sample_array)

18

In [158]:
sample_array.argmax()

18

In [159]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [160]:
np.argmin(sample_array)

0

In [161]:
np.argmax(sample_array)   #index of max

18

In [162]:
a=np.exp(sample_array)
a

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [163]:
np.average(sample_array)

10.0

In [164]:
np.argmin(sample_array)

0

In [165]:
np.var(sample_array)

30.0

In [166]:
np.mean(sample_array)

10.0

In [167]:
np.std(sample_array)

5.477225575051661

In [168]:
array=np.random.randn(3,6)
array

array([[ 0.01263982,  0.38598225,  0.31113052,  0.58930178,  0.20412458,
         0.79250307],
       [ 0.94068596, -2.23614452, -1.25902994,  0.74696633,  1.09945229,
        -1.51211365],
       [-0.18905267,  0.63669722,  1.88876213,  0.12279062, -0.94065401,
         0.61094037]])

In [169]:
np.round(array,decimals=3)

array([[ 0.013,  0.386,  0.311,  0.589,  0.204,  0.793],
       [ 0.941, -2.236, -1.259,  0.747,  1.099, -1.512],
       [-0.189,  0.637,  1.889,  0.123, -0.941,  0.611]])

In [170]:
np.round(a,decimals=3)

array([2.71800000e+00, 7.38900000e+00, 2.00860000e+01, 5.45980000e+01,
       1.48413000e+02, 4.03429000e+02, 1.09663300e+03, 2.98095800e+03,
       8.10308400e+03, 2.20264660e+04, 5.98741420e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [171]:
sports=np.array(['golf','cricket','football','volly','golf'])
sports

array(['golf', 'cricket', 'football', 'volly', 'golf'], dtype='<U8')

In [172]:
np.unique(sports)

array(['cricket', 'football', 'golf', 'volly'], dtype='<U8')

In [175]:
np.random.randint(2,3,5)

array([2, 2, 2, 2, 2])